### PR TITLE
Fix alignment in Working Files

### LINKED ISSUE #80: Alignment
Latest release causing uneven spacing, see screenshot:

issue-icons

Windows 8.1
Brackets 1.3

### PR DESCRIPTION
**Pull request by danieldevine**
Fixes #80

### CODE REVIEW

**Comment by ivogabe** [comment]
Thanks for the fix! Can you change spaces to tabs? After that I'll merge your fix.

**Comment by danieldevine** [comment]
cheers, cool extension by the way.

**Comment by danieldevine** [comment]
That should be good to go now.

**Comment by ivogabe** [comment]
Thanks!

**Pull request merged**
